spring:
  ## datasource master #
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&socketTimeout=60000
    username: root
    password: root

  datasourceslave:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&socketTimeout=60000
    username: root
    password: root


